# This is a basic workflow to help you get started with Actions

name: Runner with Dockercompose Example

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  runhitcounter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Create containers
        run: docker-compose up -d

      # Runs a set of commands using the runners shell
      - name: Test
        run: docker run --network container:webapp-frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
        
      - name: Curl to get latest hit count
        id: counterstep
        run: echo "::set-output name=counter::$(curl http://localhost:5000/)"
        
      # Create Json file with output
      - uses: Dwarak91/log-to-file@0.1
        with:
          filename: 'hit_counter_log.txt'
          logdata: ${{ steps.counterstep.outputs.counter }}
          
      - name: get log data
        run: cat hit_counter_log.txt
